---
- import_task: install_nginx.yml
- import_task: install_git.yml
- name: Lighthouse | cp from git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: "{{ lighthouse_dir }}"
  notify: Start nginx service
