---
- name: Install nginx
  ansible.builtin.import_tasks: install_nginx.yml
- name: Install git
  ansible.builtin.import_tasks: install_git.yml
- name: Lighthouse | cp from git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    version: master
    dest: "{{ lighthouse_dir }}"
  notify: Start nginx service
  